# See related documentation in https://github.com/joshcarp/sysl-printing/blob/master/docs/releasing.md
name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release-sysl:
    name: Release Sysl
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@master

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Get dependencies
        run: make deps
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: make coverage
        timeout-minutes: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SYSL_PLANTUML: http://www.plantuml.com/plantuml

      - name: Validate goreleaser config
        uses: goreleaser/goreleaser-action@master
        with:
          args: check -f .github/goreleaser_configs/.goreleaser.yml

      # GoReleaser requires Docker Hub access to push image
      - name: Login to Docker Hub
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Set env
        run: echo ::set-env name=GOVERSION::$(go version | awk '{print $3, $4;}')

      # GoReleaser release process is customized in `.goreleaser.yml` file
      - name: Release binaries and docker images via goreleaser
        uses: goreleaser/goreleaser-action@master
        with:
          args: release --rm-dist --debug -f .github/goreleaser_configs/.goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # FIXME: sysl_js hasn't been rebuilt for months and it is out of date.
      # If sysl_js works again, please add NPM_PUBLISH_TOKEN to GitHub secrets
      # and uncomment this step.
      # - name: Release sysl_js
      #   run: cd unsorted/sysl_js && NPM_AUTH_TOKEN=$ npm publish
      #   env:
      #     NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
